### ISSUE TITLE
Removing Plugin from sharedPlugins Still leaves game paused at start

### ISSUE THREAD

**Issue by Talung** [TwentyEighty/ClusterioAutoPause#1]
I have been using this mod and its great.  However, when I decided to remove it, every time I start up the cluster, it is paused at 0.05.

I went and changed the gamespeed on all the servers to 1.0, but restarting the cluster it is at 0.05.

How do I remove completely.  

Thanks

**Comment by TwentyEighty** [comment]
If it's not in shared plugins it shouldn't affect anything, have you tried
setting the game speed on all instances at the same time with the CLI tool?
node cluster_rcon.js /c game.speed = 1.0

**Comment by Talung** [comment]
Yup, and thats the weird thing.. removed it from sharedPlugins, restarted cluster set game speed via the CLI tools.  Was on in game at the time.. so saw it go through.  Stopped cluster... restarted it, and it was back on 0.05 set by the plugin... at least that was the message.

**Comment by Talung** [comment]
Alright, just tried the whole process again.  And this time it stuck.  It didn't revert back to the 0.05 run speed.

Very weird.. but now it is working as it should.  Sorry to bother.

**Comment by TwentyEighty** [comment]
Did master restart as well?

**Comment by TwentyEighty** [comment]
Oops missed the update where it was fixed. I bet earlier that master didn't restart. Well thanks for the update
